export const url_servers = {
    key_server: 'dttx',
    realm: 'lcms',
    port: '9081',
    port_socket: '9082',
    host: ['https://dttx.ictu.edu.vn'],
    ws_url: ['wss://dttx.ictu.edu.vn',],
    pageTitle: '[LCMS] - Hệ thống đào tạo từ xa',
    X_APP_ID: 'D5006F80-F239-4FBD-9D48-91EE3B1ECFD0',
    localhost: '0645451e-3396-41eb-8d02-ae39cb030cdd',
    google_client_id: '973389896263-11sa03rtspsn2fap5uo160l3opa7n62t.apps.googleusercontent.com',
    ketServer_api: `https://apps.ictu.vn:9081/tracnghiem_ket/api/v1/`,
    thikhacServer_api: `https://apps.ictu.vn:9081/thikhac/api/v1/`,
    driveFolders_id: '1LT5vL0AAVy3NxLGkNB7-OAX4cSiNcjSA',
    lectureData_id: '1pZnWJlW4C3WQsKq4B90gmCL8ORsCf3yj',
    studentData_id: '1ziFcZenGCf_qQDHkjwA7aLyPBde0od0N',
    driveImage_id: '1KaWFZTpECwlanpYovIapqWFIinsnTUVw',
    driveVideo_id: '1qzXI3D0OEnelcgOjbEtHQYJ6KTv0EM92',
    video_marker: true,
    donviquanly: 'Đại Học Thái Nguyên',
    donvitructhuoc: 'Trường Đại Học CNTT & TT',
    class_main: '',
    file_server: 'serverAws',
    title: 'TS-DTTX-ICTU',
    domain: 'https://tuyensinh-dttx.ictu.vn/',
    codeByLvl: false,
    unlimitLesson: false,
    appVersion: '2.0.00'

}
